# Generated by Django 4.0.4 on 2022-04-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='antecedents',
            field=models.TextField(blank=True),
        ),
    ]
