# Generated by Django 4.0.4 on 2022-04-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marineapp', '0002_patient_antecedents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='antecedents',
            new_name='antecedents_chirugicaux',
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents_medicaux',
            field=models.TextField(blank=True),
        ),
    ]
